### PR TITLE
fix issue #28

### PR DESCRIPTION
**Pull request by naviocean**

### CODE REVIEW

**Comment by Wufe** [comment]
Before wrapping the function in a try catch, we need to understand why this happens, so if you discovered how to reproduce, please let me know.

**Comment by naviocean** [comment]
To reproduce:
1. Enter the route with particles
2. Go to another route
3. Go back and the error will showed.

**Comment by Wufe** [comment]
Thanks @naviocean I really appreciate your help.  
I tried to reproduce the issue in a sandbox, but the error doesn't show.  
Am I missing something?

The sandbox can be found here:

[Edit Routing demo](https://codesandbox.io/s/31p352y6p1)

**Comment by Wufe** [comment]
This PR has been merged, thanks.

**Pull request merged**
